server:
  port: ${port:40100}
spring:
  application:
    name: service-search
xedu:
  elasticsearch:
    hostlist: ${eshostlist:192.168.116.129:9200} #多个结点中间用逗号分隔
    course:
      index: xedu_course
      source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_ time,start_time,end_time