server:
  port: 31000
spring:
  application:
    name: service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:wx123456@192.168.116.129:27017
      database: xedu_cms
  rabbitmq:
    host: 192.168.116.129
    port: 5672
    username: admin
    password: admin
    virtualHost: /
xedu:
  mq:
    queue: queue_cms_postpage_01 #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID