server:
  port: 31450
spring:
  application:
    name: service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:wx123456@192.168.116.129:27017
      database: xedu_media
#rabbitmq配置
  rabbitmq:
    host: 192.168.116.129
    port: 5672
    username: admin
    password: admin
    virtualHost: /
service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: /Users/wx/project/XEduCode/XEdu-UI/video/
  ffmpeg-path: ffmpeg